version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: restaurantos-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: restaurantOS

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: restaurantos-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: production
      MONGODB_URI: mongodb+srv://alnayanalbashir4:alnayanhealth@health.mtmv4.mongodb.net/restaurantOS?retryWrites=true&w=majority
      JWT_SECRET: change_this_to_a_very_long_random_secret_string_at_least_64_chars
      JWT_EXPIRES_IN: 7d
      FRONTEND_URL: https://restaurantms-frontend.onrender.com
      # Add your Cloudinary & Stripe keys here or via .env
    depends_on:
      - mongo
    volumes:
      - ./backend/src:/app/src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: restaurantos-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: https://restaurantms-backend.onrender.com/api
      NEXT_PUBLIC_SOCKET_URL: https://restaurantms-backend.onrender.com
    depends_on:
      - backend

volumes:
  mongo_data:

